In [2]:
from google.colab import files
uploaded = files.upload()

Saving tweets_bitcoin_week_1_20_06_2022_19_30_48.csv to tweets_bitcoin_week_1_20_06_2022_19_30_48.csv

In [3]:
#to ignore warnings
import warnings
warnings.filterwarnings('ignore')


import pandas as pd
bt1 = pd.read_csv('tweets_bitcoin_week_1_20_06_2022_19_30_48.csv')
bt1.head()

,Unnamed: 0,id,date,content,user_name,profile_verified_status,reply_count,retweet_count,likes_count,retweetedTweet,quotedTweet,hashtags,cashtags,place
0,0,1213971406628765697,2020-01-05 23:51:52+00:00,Side by side view of GOLD and BITCOIN\n\nThese...,RookieXBT,True,3,21,108,NaN,NaN,NaN,"['BTCUSD', 'BTC', 'XAU', 'XAUUSD']",NaN
1,1,1213968448566501378,2020-01-05 23:40:07+00:00,"Right now, 1 btc is worth roughly 40 hours of ...",marcelamdax,False,10,3,61,NaN,NaN,NaN,NaN,NaN
2,2,1213967489840730112,2020-01-05 23:36:18+00:00,"$gold testing major 0.618 from 2011 highs, if ...",SmartContracter,False,22,29,214,NaN,NaN,NaN,"['gold', 'btc', 'xau']",NaN
3,3,1213967406663647234,2020-01-05 23:35:58+00:00,Gold SPIKES To $1590 (Multi-Year Highs) &gt; h...,ShortSqueezed1,False,1,9,24,NaN,NaN,"['silver', 'Iran', 'gold', 'Kenya', 'US', 'new...",NaN,NaN
4,4,1213966899534413824,2020-01-05 23:33:57+00:00,PoS Bitcoin on Cosmos will dominate as the cur...,jaesustein,False,9,12,67,NaN,NaN,NaN,NaN,NaN

In [4]:
bt1.shape

(3699, 14)

In [5]:
bt1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3699 entries, 0 to 3698
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unnamed: 0               3699 non-null   int64
 1   id                       3699 non-null   int64
 2   date                     3699 non-null   object
 3   content                  3699 non-null   object
 4   user_name                3699 non-null   object
 5   profile_verified_status  3699 non-null   bool
 6   reply_count              3699 non-null   int64
 7   retweet_count            3699 non-null   int64
 8   likes_count              3699 non-null   int64
 9   retweetedTweet           0 non-null      float64
 10  quotedTweet              426 non-null    object
 11  hashtags                 1577 non-null   object
 12  cashtags                 1122 non-null   object
 13  place                    49 non-null     object
dtypes: bool(1), float64(1), int64(5), object(7)
memory usage: 379.4+ KB

In [6]:
bt1.describe()

,Unnamed: 0,id,reply_count,retweet_count,likes_count,retweetedTweet
count,3699.000000,3.699000e+03,3699.000000,3699.000000,3699.000000,0.0
mean,1849.000000,1.214890e+18,16.532306,25.809949,127.636388,NaN
std,1067.953651,6.856052e+14,87.068089,171.498135,1885.865936,NaN
min,0.000000,1.213612e+18,0.000000,0.000000,11.000000,NaN
25%,924.500000,1.214321e+18,2.000000,3.000000,28.000000,NaN
50%,1849.000000,1.214866e+18,4.000000,7.000000,44.000000,NaN
75%,2773.500000,1.215439e+18,9.000000,17.000000,85.000000,NaN
max,3698.000000,1.216145e+18,3070.000000,8236.000000,113970.000000,NaN

In [7]:
bt1.columns

Index(['Unnamed: 0', 'id', 'date', 'content', 'user_name',
       'profile_verified_status', 'reply_count', 'retweet_count',
       'likes_count', 'retweetedTweet', 'quotedTweet', 'hashtags', 'cashtags',
       'place'],
      dtype='object')

In [8]:
bt1.nunique()

Unnamed: 0                 3699
id                         3699
date                       3679
content                    3697
user_name                  1568
profile_verified_status       2
reply_count                 171
retweet_count               211
likes_count                 429
retweetedTweet                0
quotedTweet                 360
hashtags                    949
cashtags                    360
place                        36
dtype: int64

In [9]:
bt1['user_name'].unique

<bound method Series.unique of 0             RookieXBT
1           marcelamdax
2       SmartContracter
3        ShortSqueezed1
4            jaesustein
             ...
3694     patrickluberus
3695         runolgarun
3696          BigChonis
3697     cryptorecruitr
3698      TreosOfficial
Name: user_name, Length: 3699, dtype: object>

In [10]:
bt1.isnull().sum()

Unnamed: 0                    0
id                            0
date                          0
content                       0
user_name                     0
profile_verified_status       0
reply_count                   0
retweet_count                 0
likes_count                   0
retweetedTweet             3699
quotedTweet                3273
hashtags                   2122
cashtags                   2577
place                      3650
dtype: int64

In [11]:
# !pip install dataprep
# from dataprep.eda import plot
# plot(bt1)

In [ ]:
# from dataprep.eda import plot
# plot(bt1)

In [ ]:
# from dataprep.eda import create_report
# report = create_report(bt1)

# report.show()

In [12]:
bt1
bt1['date']

bt1['Dates'] = pd.to_datetime(bt1['date']).dt.date
bt1['Time'] = pd.to_datetime(bt1['date']).dt.time
bt1['Dates']

0       2020-01-05
1       2020-01-05
2       2020-01-05
3       2020-01-05
4       2020-01-05
           ...
3694    2020-01-11
3695    2020-01-11
3696    2020-01-11
3697    2020-01-11
3698    2020-01-11
Name: Dates, Length: 3699, dtype: object

In [13]:
days = bt1['Dates'].unique()
print(days)
d1 = bt1[bt1['Dates']==days[0]]
#bt1.groupby(by = ['Dates'], axis = 0).sum()
#gb.head(5)
print(d1)

[datetime.date(2020, 1, 5) datetime.date(2020, 1, 6)
 datetime.date(2020, 1, 7) datetime.date(2020, 1, 8)
 datetime.date(2020, 1, 9) datetime.date(2020, 1, 10)
 datetime.date(2020, 1, 11)]
     Unnamed: 0                   id                       date  \
0             0  1213971406628765697  2020-01-05 23:51:52+00:00
1             1  1213968448566501378  2020-01-05 23:40:07+00:00
2             2  1213967489840730112  2020-01-05 23:36:18+00:00
3             3  1213967406663647234  2020-01-05 23:35:58+00:00
4             4  1213966899534413824  2020-01-05 23:33:57+00:00
..          ...                  ...                        ...
401         401  1213615043453038592  2020-01-05 00:15:48+00:00
402         402  1213613751364141057  2020-01-05 00:10:40+00:00
403         403  1213612997266083841  2020-01-05 00:07:41+00:00
404         404  1213612643166097409  2020-01-05 00:06:16+00:00
405         405  1213612233722388480  2020-01-05 00:04:39+00:00

                                               content        user_name  \
0    Side by side view of GOLD and BITCOIN\n\nThese...        RookieXBT
1    Right now, 1 btc is worth roughly 40 hours of ...      marcelamdax
2    $gold testing major 0.618 from 2011 highs, if ...  SmartContracter
3    Gold SPIKES To $1590 (Multi-Year Highs) &gt; h...   ShortSqueezed1
4    PoS Bitcoin on Cosmos will dominate as the cur...       jaesustein
..                                                 ...              ...
401  Bitcoin is a savings plan and a hedge against ...       ihatecodee
402  The hate against @nakamoto contributors for no...    iamDCinvestor
403  Important message ~ 5 months before the Bitcoi...       APompliano
404  Going all in on #IOTA felt nice today! Future ...       ThomasQvOG
405  $BTC\n\nOne or the other, i'm ready for both. ...          imBagsy

     profile_verified_status  reply_count  retweet_count  likes_count  \
0                       True            3             21          108
1                      False           10              3           61
2                      False           22             29          214
3                      False            1              9           24
4                      False            9             12           67
..                       ...          ...            ...          ...
401                    False            4              5           44
402                    False            9              3          126
403                     True          138            308         1549
404                    False           10             19          135
405                    False            2              1           23

     retweetedTweet quotedTweet  \
0               NaN         NaN
1               NaN         NaN
2               NaN         NaN
3               NaN         NaN
4               NaN         NaN
..              ...         ...
401             NaN         NaN
402             NaN         NaN
403             NaN         NaN
404             NaN         NaN
405             NaN         NaN

                                              hashtags  \
0                                                  NaN
1                                                  NaN
2                                                  NaN
3    ['silver', 'Iran', 'gold', 'Kenya', 'US', 'new...
4                                                  NaN
..                                                 ...
401                                                NaN
402                                                NaN
403                                                NaN
404                                ['IOTA', 'Bitcoin']
405                                                NaN

                               cashtags place       Dates      Time
0    ['BTCUSD', 'BTC', 'XAU', 'XAUUSD']   NaN  2020-01-05  23:51:52
1                                   NaN   NaN  2020-01-05  23:40:07
2                ['gold', 'btc', 'xau']   NaN  2020-01-05  23:36:18
3                                   NaN   NaN  2020-01-05  23:35:58
4                                   NaN   NaN  2020-01-05  23:33:57
..                                  ...   ...         ...       ...
401                                 NaN   NaN  2020-01-05  00:15:48
402                                 NaN   NaN  2020-01-05  00:10:40
403                                 NaN   NaN  2020-01-05  00:07:41
404                            ['IOTA']   NaN  2020-01-05  00:06:16
405                             ['BTC']   NaN  2020-01-05  00:04:39

[406 rows x 16 columns]

In [14]:
# d1g = d1.groupby('profile_verified_status')
# print(d1g)

# d1g = d1.groupby(['profile_verified_status'])
# d1g.describe()
# d1g.head()

d1g_sum = d1.groupby(['profile_verified_status']).sum()
d1g_sum

# d1g = d1.groupby(['profile_verified_status']).describe()
# print(d1g)

# df_eda["sex"].value_counts()
# heart_data.drop(['time'], axis=1, inplace = True)

,Unnamed: 0,id,reply_count,retweet_count,likes_count,retweetedTweet
profile_verified_status,,,,,,
False,70035.0,4.139096e+20,5178.0,6242.0,28906.0,0.0
True,12180.0,7.889848e+19,4337.0,3792.0,15903.0,0.0

In [16]:
d1g_count = d1.groupby(['profile_verified_status']).count()
d1g_count

,Unnamed: 0,id,date,content,user_name,reply_count,retweet_count,likes_count,retweetedTweet,quotedTweet,hashtags,cashtags,place,Dates,Time
profile_verified_status,,,,,,,,,,,,,,,
False,341,341,341,341,341,341,341,341,0,37,133,86,7,341,341
True,65,65,65,65,65,65,65,65,0,14,28,10,1,65,65

In [17]:
d1
d1["user_name"].value_counts()
# print(d1["user_name"].value_counts())
# d1["user_name"].value_counts()
# d1["user_count"] = d1["user_name"].value_counts()


# print(d1.sort_values("user_name", inplace = True))

Bitsahara          5
cryptorecruitr     5
notgrubles         5
PeterMcCormack     4
theonevortex       4
                  ..
ph_lux             1
mr_kristof007      1
WomanBlockchain    1
THE_FREE_COIN      1
ThomasQvOG         1
Name: user_name, Length: 312, dtype: int64

In [18]:
d1['user_count'] = d1.groupby('user_name')['user_name'].transform('count')
print(d1.sort_values(by=['user_name']).to_string())

     Unnamed: 0                   id                       date                                                                                                                                                                                                                                                                                                                                             content        user_name  profile_verified_status  reply_count  retweet_count  likes_count  retweetedTweet                                                     quotedTweet                                                                                                                                                                                                              hashtags                                                                                                                                     cashtags                                                                                                                                                                        place       Dates      Time  user_count
319         319  1213708530169106437  2020-01-05 06:27:17+00:00                                                                                                                           Even more #xrp pairings coming . @BitrueOfficial does make #xrpthestandard . set up an account if you haven't and make sure to follow them on Twitter 💯 \n#cryptocurrency #bitcoin\n#blockchain \nhttps://t.co/jNxyGFcqLh     1000bonesXrp                    False            2             11           57             NaN                                                             NaN                                                                                                                                                  ['xrp', 'xrpthestandard', 'cryptocurrency', 'bitcoin', 'blockchain']                                                                                                                                          NaN                                                                                                                                                                          NaN  2020-01-05  06:27:17           1
237         237  1213815577527095296  2020-01-05 13:32:39+00:00                                                                                               IMO co-integration between #bitcoin price &amp; stock-to-flow means all network effects march lockstep: Investors, Speculators, Merchants, Consumers, Miners and Developers together ... demand &amp; supply, like clockwork! https://t.co/7Ozq2Y9eVd   100trillionUSD                    False           35            190          933             NaN                                                             NaN                                                                                                                                                                                                           ['bitcoin']                                                                                                                                          NaN                                                                                                                                                                          NaN  2020-01-05  13:32:39           1
251         251  1213801115357237250  2020-01-05 12:35:11+00:00                              If you’re the owner or developer of a BitCoin app or service, https://t.co/LrXR0GSKLU invites you to create your listing for FREE. \n\nWe will highlight your ad on our homepage &amp; category sliders for the life of your project\n\nThank you for your contributions to the #BSV ecosystem https://t.co/xOGSHn4lrh       5centspace                    False            0             10           24             NaN                                                             NaN                                                                                                                                                                                                               ['BSV']                                                                                                                                          NaN                                                                                                                                                                          NaN  2020-01-05  12:35:11           1
222         222  1213823733464518656  2020-01-05 14:05:04+00:00                                   #BTC $BTC #BTCUSD Popcorn! 🍿\n\nHey Silly Bears! 🐻\nIf you want cheap "200MA" Cornflakes, you better UP selling at this E wave, falling wedge, 5 year old trendline / 2 year supportline, where EMA's are about to cross bullish atm.\nNvm halving and new Institutional gamblers etc🤦‍♂️ https://t.co/3SPjBZyDzK        888Velvet                    False            4              6           38             NaN                                                             NaN                                                                                                                                                                                                     ['BTC', 'BTCUSD']                                                                                                                                      ['BTC']                                                                                                                                                                          NaN  2020-01-05  14:05:04           1
403         403  1213612997266083841  2020-01-05 00:07:41+00:00                                                           Important message ~ 5 months before the Bitcoin halving:\n\n- BTC is very volatile\n- You can lose all of your money\n- Only invest what is ok to lose\n- Twitter is not investment advice\n- Don't buy BTC with credit cards\n- Keep low time preference\n- Do your own research\n\n🙏🏽🙏🏽       APompliano                     True          138            308         1549             NaN                                                             NaN                                                                                                                                                                                                                   NaN                                                                                                                                          NaN                                                                                                                                                                          NaN  2020-01-05  00:07:41           2
223         223  1213823517617250304  2020-01-05 14:04:13+00:00                                                                                                                                                                        This week’s letters to investors are starting 2020 with a bang.\n\nDon’t miss the most popular newsletter in Bitcoin and crypto.\n\nSubscribe today: https://t.co/4kI0JLsPfL       APompliano                     True            5             14           81             NaN                                                             NaN                                                                                                                                                                                                                   NaN                                                                                                                                          NaN                                                                                                                                                                          NaN  2020-01-05  14:04:13           2
248         248  1213802892110573570  2020-01-05 12:42:15+00:00                   JOHN MCAFEE podcast LIVE NOW.\n\nCryptocurrency\nRussian Roulette\nWhat makes a company actually successful\nKIng of the Jungle\nThe Next Big Thing\n\nDIRECT LINKS:\n\nhttps://t.co/VeWRIhkTvu\n\nhttps://t.co/4dcs4PWwZC\n\niTunes, TunieIn, Spotify\n\n@officialmcafee \n#podcast \n#bitcoin \n#Wisdom https://t.co/JZ5bxAdZsa   ARemarkableMan                    False            8              7           48             NaN                                                             NaN                                                                                                                                                                                      ['podcast', 'bitcoin', 'Wisdom']                                                                                                                                          NaN                                                                                                                                                                          NaN  2020-01-05  12:42:15           1
139         139  1213878031011500032  2020-01-05 17:40:50+00:00                                                                                                                                                                                    Short “Bitcoin halving is not priced in”\n\nLong “Ethereum as the hypergrowth-meta-startup reinventing value, property, finance &amp; politics is not priced in”       AlexMasmej                    False            0              5           17             NaN                                                             NaN                                                                                                                                                                                                                   NaN                                                                                                                                          NaN                                                                                                                                                                          NaN  2020-01-05  17:40:50           1
232         232  1213818514663968769  2020-01-05 13:44:20+00:00                              🚀#AirdropAlert🚀\n\n👉#Trading Contest Live! https://t.co/7pxGcV56vO&lt;&lt;\n\n🪂#Retweet🪂\n\n👉#Reply with your #ERC20 wallet before 1/10/2020 for your #chance to #win!\n\n#Airdrops #cryptocurrency #CryptoGiveaway #crypto #bitcoin #Alpha #Airdrop #Cryptohopper #Bitcoin #btc #BountyHunter https://t.co/iplRcOkx0H      Alpha_Token                    False          196            126          124             NaN                                                             NaN  ['AirdropAlert', 'Trading', 'Retweet', 'Reply', 'ERC20', 'chance', 'win', 'Airdrops', 'cryptocurrency', 'CryptoGiveaway', 'crypto', 'bitcoin', 'Alpha', 'Airdrop', 'Cryptohopper', 'Bitcoin', 'btc', 'BountyHunter']                                                                                                                                          NaN                                                                                                                                                                          NaN  2020-01-05  13:44:20           1
205         205  1213841384240812034  2020-01-05 15:15:12+00:00                                                                                                                                                                                                        Best usage of your time? Educate yourself and read the #bitcoin book recommendations by my podcast guests. The list: https://t.co/Wjs3JZrFCv       AnitaPosch                    False            2              6           21             NaN                                                             NaN                                                                                                                                                                                                           ['bitcoin']                                                                                                                                          NaN                                                                                                                                                                          NaN  2020-01-05  15:15:12           1
340         340  1213669174867681281  2020-01-05 03:50:54+00:00                                                                                                                                                                                                                 Bitcoin 1D MAs twining. This usually leads to an impulsive move.\n\nEyeing 8500-9100. Invalidation &lt;6600 https://t.co/LwJI6f1osq   AnondranCrypto                    False            4              4           26             NaN                                                             NaN                                                                                                                                                                                                                   NaN                                                                                                                                          NaN                                                                                                                                                                          NaN  2020-01-05  03:50:54           1
19           19  1213952088402747394  2020-01-05 22:35:06+00:00                                                                                    The US financial system is completely solvent, yet the Fed has added $400B to their balance sheet in the last 3 months. Sure. ⏳\n\nThe youth instinctively know the system the boomers are leaving them is broken.\n\n#Bitcoin was created for this environment.     AnselLindner                    False            2             11           52             NaN                                                             NaN                                                                                                                                                                                                           ['Bitcoin']                                                                                                                                          NaN                                                                                                                                                                          NaN  2020-01-05  22:35:06           1
104         104  1213891388020084736  2020-01-05 18:33:54+00:00                                                                                                                                                                                                                                                            John McAfee Turns His Back on Bitcoin, Refuses to Eat His Words. https://t.co/VMlWfJTqVB      AssetsDaily                    False            4              2           17             NaN                                                             NaN                                                                                                                                                                                                                   NaN                                                                                                                                          NaN                                                                                                                                                                          NaN  2020-01-05  18:33:54           1
285         285  1213762077002797056  2020-01-05 10:00:04+00:00                                                                                                                       The $BSV blockchain processed 396k tx on 2 Dec, compared to $BTC's 274k thanks to increased block sizes, which was a major move to improve UX-a key metric needed to drive mass adoption &amp; usage\nhttps://t.co/RriFyntoqz          BGAP600                    False            0             18           31             NaN                                                             NaN                                                                                                                                                                                                                   NaN                                                                                                                               ['BSV', 'BTC']                                                                                                                                                                          NaN  2020-01-05  10:00:04           1
324         324  1213693192916406272  2020-01-05 05:26:21+00:00                                                                                                                                                                                                                                              Shorted BCH/BTC/ETH now at 225/7400/135 to hedge my Bitcoin position. They are all garbage. BSV rules.        BHoarder1                    False            1              1           19             NaN                                                             NaN                                                                                                                                                                                                                   NaN                                                                                                                                          NaN                                                                                                                                                                          NaN  2020-01-05  05:26:21           1
30           30  1213942102771433472  2020-01-05 21:55:25+00:00                                                          Noob: I just bought a little Bitcoin and want to learn more.\n\nShitcoiner: Ooh, you're interested in Bitcoin? I'm pro Bitcoin, but it has many flaws. Let me introduce you to this shitcoin that solves all these problems. *doesn't mention massive personal investment in said shitcoin         BTCKris_                    False            3              9          111             NaN                                                             NaN                                                                                                                                                                                                                   NaN                                                                                                                                          NaN                                                                                                                                                                          NaN  2020-01-05  21:55:25           1

In [19]:
d1.sort_values(by=['user_count'])
  
sub_d1 = d1[d1.groupby('user_name').user_name.transform('count')<=3].copy()
print(sub_d1.to_string())
# print(sub_d1)
sub_d1.shape

# print(df.to_string())

     Unnamed: 0                   id                       date                                                                                                                                                                                                                                                                                                                                             content        user_name  profile_verified_status  reply_count  retweet_count  likes_count  retweetedTweet                                                     quotedTweet                                                                                                                                                                                                              hashtags                                                                                                                                     cashtags                                                                                                                                                                        place       Dates      Time  user_count
0             0  1213971406628765697  2020-01-05 23:51:52+00:00                                                                                           Side by side view of GOLD and BITCOIN\n\nThese assets are often seen as a hedge against world crisis\n\nBitcoin has alot of room to run.\n\nCredits to @Bill87926598 on @tradingview for inspiration\n\n$BTCUSD $BTC $XAU $XAUUSD https://t.co/JPv0sNfywJ        RookieXBT                     True            3             21          108             NaN                                                             NaN                                                                                                                                                                                                                   NaN                                                                                                           ['BTCUSD', 'BTC', 'XAU', 'XAUUSD']                                                                                                                                                                          NaN  2020-01-05  23:51:52           1
1             1  1213968448566501378  2020-01-05 23:40:07+00:00                                                                                                                                                                                                              Right now, 1 btc is worth roughly 40 hours of my time. \n\nExpect to see that number increase to at least 400 hours within the decade.      marcelamdax                    False           10              3           61             NaN                                                             NaN                                                                                                                                                                                                                   NaN                                                                                                                                          NaN                                                                                                                                                                          NaN  2020-01-05  23:40:07           1
2             2  1213967489840730112  2020-01-05 23:36:18+00:00                                                                                                    $gold testing major 0.618 from 2011 highs, if btc taught us anything, you don't fuck with the high timeframe 0.618 🤷‍♀️\n\nif you dont have the balls to short it for the love of god atleast take profit 😂\n\n$btc $xau https://t.co/GZKqZdyZEZ  SmartContracter                    False           22             29          214             NaN                                                             NaN                                                                                                                                                                                                                   NaN                                                                                                                       ['gold', 'btc', 'xau']                                                                                                                                                                          NaN  2020-01-05  23:36:18           2
3             3  1213967406663647234  2020-01-05 23:35:58+00:00                                                                                                                                                     Gold SPIKES To $1590 (Multi-Year Highs) &gt; https://t.co/Jjw72Gnvdn  #silver #Iran #gold #Kenya #US #news #bitcoin #Iraq #Soleimani #Baghdad #Pentagon #Trump #war #drone #oil #qe #QE4 #China   ShortSqueezed1                    False            1              9           24             NaN                                                             NaN                                                        ['silver', 'Iran', 'gold', 'Kenya', 'US', 'news', 'bitcoin', 'Iraq', 'Soleimani', 'Baghdad', 'Pentagon', 'Trump', 'war', 'drone', 'oil', 'qe', 'QE4', 'China']                                                                                                                                          NaN                                                                                                                                                                          NaN  2020-01-05  23:35:58           1
4             4  1213966899534413824  2020-01-05 23:33:57+00:00                                                             PoS Bitcoin on Cosmos will dominate as the currency of choice for the next millennium of commerce on this planet earth. Those who do not follow the way will not be recorded on the Cosmos, and your existence will suffer a slow heat death. End of times is here, preserve energy. ⚛️       jaesustein                    False            9             12           67             NaN                                                             NaN                                                                                                                                                                                                                   NaN                                                                                                                                          NaN                                                                                                                                                                          NaN  2020-01-05  23:33:57           1
5             5  1213965121933860866  2020-01-05 23:26:54+00:00                                                                                                                                                                                                          Gold popping big again. Gold may be the biggest % winner this year of anything, aside from Bitcoin.  I expect 30% upside on gold for 2020.    GarethSoloway                     True            2              2           28             NaN                                                             NaN                                                                                                                                                                                                                   NaN                                                                                                                                          NaN                                                                                                                                                                          NaN  2020-01-05  23:26:54           1
6             6  1213958309956460544  2020-01-05 22:59:50+00:00                                                                           👥 start a public telegram chat\n\n💰 make a centimillionaire the admin\n\n🔑 tell people they should talk about “crypto”\n\n🚫 kick out people who like bitcoin\n\n😵 be shocked when within one day it becomes a cesspool of incoherent ramblings about bsv, hex, and ripple    udiWertheimer                    False            8             16          212             NaN                                                             NaN                                                                                                                                                                                                                   NaN                                                                                                                                          NaN                                                                                                                                                                          NaN  2020-01-05  22:59:50           3
7             7  1213957963670589440  2020-01-05 22:58:27+00:00                                     It’s been a loooong time since I saw a coin/token doing this ! Moving totally independent of #BTC. Yup.. it’s FOMO. But ther is something to get exited about. The more I learn the more I want to be in #CSC \nIt’s build on #XRP and might take the gambling crypto industry #1. Spot https://t.co/IeJHKKLlys    crypto_rasmus                    False            2             14           38             NaN                                                             NaN                                                                                                                                                                                                 ['BTC', 'CSC', 'XRP']                                                                                                                                          NaN                                                                                                                                                                          NaN  2020-01-05  22:58:27           1
9             9  1213956705706561538  2020-01-05 22:53:27+00:00                                                                                                                                                                                              Can one take a vow of silence and still tweet?\n\nCan one take a vow of chastity and still sext?\n\nCan one take a vow of poverty and collect bitcoin?  Talk_To_The_Hat                    False            6              5           29             NaN                                                             NaN                                                                                                                                                                                                                   NaN                                                                                                                                          NaN                                                                                                                                                                          NaN  2020-01-05  22:53:27           1
10           10  1213956638467604480  2020-01-05 22:53:11+00:00                                                                                                      Just had a friend contact me out of the blue saying he wanted to buy some Bitcoin to hold for at least 10 years. He recently read @saifedean’s The Bitcoin Standard and fell down the rabbit hole after that.\n\nWeak Hands -&gt; Strong Hands        lylepratt                    False            3              2           80             NaN                                                             NaN                                                                                                                                                                                                                   NaN                                                                                                                                          NaN                                                                                                                                                                          NaN  2020-01-05  22:53:11           1
12           12  1213956358732763139  2020-01-05 22:52:04+00:00                                                                                                                           "𝐓𝐡𝐞 𝐡𝐢𝐬𝐭𝐨𝐫𝐲 𝐨𝐟 𝐦𝐚𝐧𝐤𝐢𝐧𝐝 𝐢𝐬 𝐭𝐡𝐞 𝐡𝐢𝐬𝐭𝐨𝐫𝐲 𝐨𝐟 𝐦𝐨𝐧𝐞𝐲 𝐥𝐨𝐬𝐢𝐧𝐠 𝐯𝐚𝐥𝐮𝐞."\n𝘔𝘪𝘭𝘵𝘰𝘯 𝘍𝘳𝘪𝘦𝘥𝘮𝘢𝘯\n\nThis is about to change with #Bitcoin.\n\nHere is what Milton Friedman said about future e-cash money in 1996: https://t.co/ExEjEVZ6Tc         MMCrypto                     True            8             16           65             NaN                                                             NaN                                                                                                                                                                                                           ['Bitcoin']                                                                                                                                          NaN                                                                                                                                                                          NaN  2020-01-05  22:52:04           1
13           13  1213955986010099712  2020-01-05 22:50:35+00:00                                                                                                                                                                                                                                                                                                                      How much is 1 BTC worth to you        zackvoell                    False          210              8          156             NaN                                                             NaN                                                                                                                                                                                                                   NaN                                                                                                                                          NaN                                                                                                                                                                          NaN  2020-01-05  22:50:35           1
14           14  1213955981849374721  2020-01-05 22:50:34+00:00                                                  Are those who like “shitcoins” inherently “anti-bitcoin”?\n\nCan’t people just take the OG (open source) idea of Satoshi, &amp; build from it.. w/o being *anti* anything?\n\nIsn’t that what freedom is about?\n\nConfusing marketing is one thing, but  “pro alts” != “anti bitcoin” necessarily           MsHodl                    False           28              4           71             NaN                                                             NaN                                                                                                                                                                                                                   NaN                                                                                                                                          NaN                                                                                                                                                                          NaN  2020-01-05  22:50:34           1
15           15  1213955523713753089  2020-01-05 22:48:45+00:00                                                                                                                                                                                                                                                                Kinda tempted to send 1 $BTC to Ogre just to shake things up with degen market buys.    cryptofrog202                    False            6              0           19             NaN                                                             NaN                                                                                                                                                                                                                   NaN                                                                                                                                      ['BTC']                                                                                                                                                                          NaN  2020-01-05  22:48:45           1
16           16  1213954489075609600  2020-01-05 22:44:39+00:00                                                                                                                                                                                                                                                                                            $BTC - The Plan\n\nLet's get it! https://t.co/qfTfZBGvUh        TraderKoz                    False            6              2           68             NaN                                                             NaN                                                                                                                                                                                                                   NaN                                                                                                                                      ['BTC']                                                                                                                                                                          NaN  2020-01-05  22:44:39           1
17           17  1213954477650272259  2020-01-05 22:44:36+00:00                                                                                                                                                                             Pro-BTC (adj.): someone who spends most of their time creating, selling, or promoting altcoins but has a bag of bitcoin just in case the number goes up \n\n👎 @nakamoto             skwp                    False            3             10           77             NaN                                                             NaN                                                                                                                                                                                                                   NaN                                                                                                                                          NaN                                                                                                                                                                          NaN  2020-01-05  22:44:36           1

(363, 17)

In [61]:
# #tweet cleaning examples

# import re
# from bs4 import BeautifulSoup

# ex_txt ='''The link to @Naveen kumar \\n ,<br> this post is https://stackoverflow.com/questions/11331982/how-to-remove-any-url-within-a-string-in-python awsome'''
# print(ex_txt)

# # clean = re.compile('<.*?>')
# # clean_ex_txt = re.sub(clean, '', ex_txt) # Removes html tags
 
# # clean_ex_txt = BeautifulSoup(ex_txt, "lxml").text
# # clean_ex_txt = re.sub('\\n', '', ex_txt) #Removes the '\n' which is breaking the tweet
# clean_ex_txt = re.sub('@[A-Za-z0-9]+', '', ex_txt)
# clean_ex_txt = re.sub('https?:\/\/\S+', '', ex_txt) # Removes hyperlinks

# print(clean_ex_txt)

In [60]:
#cleaning tweets 
import re
def cleanTweet(tweet):
  tweet = re.sub('#[A-Za-z0-9]+', '', tweet) # Removes all words starting with #
  tweet = re.sub('@[A-Za-z0-9]+', '', tweet) # Removes all words starting with @
  tweet = re.sub('\\n', '', tweet) # Pretends from breaking the tweet
  tweet = re.sub('https?:\/\/\S+', '', tweet) # Removes hyperlinks
  tweet 
  return tweet

#Adding new column cleaned_tweets
sub_d1['cleaned_tweets'] = sub_d1['content'].apply(cleanTweet) 
sub_d1.head()

,Unnamed: 0,id,date,content,user_name,profile_verified_status,reply_count,retweet_count,likes_count,retweetedTweet,quotedTweet,hashtags,cashtags,place,Dates,Time,user_count,cleaned_tweets
0,0,1213971406628765697,2020-01-05 23:51:52+00:00,Side by side view of GOLD and BITCOIN\n\nThese...,RookieXBT,True,3,21,108,NaN,NaN,NaN,"['BTCUSD', 'BTC', 'XAU', 'XAUUSD']",NaN,2020-01-05,23:51:52,1,Side by side view of GOLD and BITCOINThese ass...
1,1,1213968448566501378,2020-01-05 23:40:07+00:00,"Right now, 1 btc is worth roughly 40 hours of ...",marcelamdax,False,10,3,61,NaN,NaN,NaN,NaN,NaN,2020-01-05,23:40:07,1,"Right now, 1 btc is worth roughly 40 hours of ..."
2,2,1213967489840730112,2020-01-05 23:36:18+00:00,"$gold testing major 0.618 from 2011 highs, if ...",SmartContracter,False,22,29,214,NaN,NaN,NaN,"['gold', 'btc', 'xau']",NaN,2020-01-05,23:36:18,2,"$gold testing major 0.618 from 2011 highs, if ..."
3,3,1213967406663647234,2020-01-05 23:35:58+00:00,Gold SPIKES To $1590 (Multi-Year Highs) &gt; h...,ShortSqueezed1,False,1,9,24,NaN,NaN,"['silver', 'Iran', 'gold', 'Kenya', 'US', 'new...",NaN,NaN,2020-01-05,23:35:58,1,Gold SPIKES To $1590 (Multi-Year Highs) &gt; ...
4,4,1213966899534413824,2020-01-05 23:33:57+00:00,PoS Bitcoin on Cosmos will dominate as the cur...,jaesustein,False,9,12,67,NaN,NaN,NaN,NaN,NaN,2020-01-05,23:33:57,1,PoS Bitcoin on Cosmos will dominate as the cur...